### ISSUE TITLE
Herbarium Guides 2024 Q2 updates

### ISSUE THREAD

**Issue by nms419** [NHMDenmark/Herbarium-Sheets-workstation#100]
A place to keep track of any needed updates to the Herbarium Imaging Guide and the Herbarium Barcoding Guide in the timeframe of April - June 2024. 

A current edit of the guides is in process and can be found at N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\GUIDES\Editing in process. 

Please check there to see what changes are currently being implemented. 

Feedback, comments and wishes for updates welcome, please leave them as a comment on this issue or in a comment in the word file if pertaining to a specific section. 

**Updates to be implemented:** 

- [x] Incorporate a convention for naming white balance presets (see #99) 
- [x] Update the guides to reflect current workflow around carts 
- [x] Make the guides less NHMD specific 
- [x] Incorporate indexes and linkable headlines
- [x] Add "One folder pr. digitiser" to Imaging Guide for Ingestion Client purposes
- [x] How to deal with middle authors -> add to Digi app Guide
- [x] Add 'How to Turn Off LCD Monitor' to Imaging Guide

**Comment by RebekkaML** [comment]
Another thing might be Issue 85 from the Issue log, that we have to make 1 image folder per person and ingest them separately so we can always assign it to the correct digitizer in the ingestion client.

**Comment by RebekkaML** [comment]
If there is a taxon that has Authors for different taxonomic levels given on the folder (one author for Species, another for subspecies etc.), we only enter the last author in the taxon field in the app, because it doesn't recognoze the author names in the middle of the taxon as authors. (see https://github.com/NHMDenmark/Mass-Digitizer/issues/503)

Example: "Hieracium lycopifolium Froel. subsp. linaaense Wiinst" -> Hieracium lycopifolium var. linaaense Wiinst

**Comment by nms419** [comment]
I've now updated all three guides in the editing folder. Please give them a read through and provide feedback by commenting in the word file. 

The Barcoding Guide has received the most edits, and I've tried to add a section defining what a specimen is based on it's data set, to specify what we are assigning barcodes to. Let me know if that section makes sense or needs to be edited down etc. 

The Imaging Guide is more or less the same with just a few updates to the workflow (see top post). 

The Digi App Guide still has a lot of unresolved issues (mainly to do with AU/NHMA protocol), but any feedback on it would be appreciated.

Thank you ^^

**Comment by AstridBVW** [comment]
I have made some edits (with track changes) and written some comments to The Barcoding Guide. The edits are mainly clarification of steps to make sure there are no misunderstandings. Hope it is helpful. It took me a while to go through so unfortunately I do not have time to read through the two other guides today.

**Comment by nms419** [comment]
Comments have been incorporated and Herbarium Guides have been moved to the 'Masters' folder. I'll print physical copies next time I'm at Priorparken and add a shortcut to the desktop.
