### ISSUE TITLE
Send WORKHERB0001 Fuji GFX100S out for Service in week 29

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#106]
Chelsea has been in contact with Carsten Iversen at Goecker about getting our cameras serviced. 

Goecker can 
- Check if they have the latest firmware installed (and if not, install it)
- Clean the camera
- Check if all ports are functioning properly

Carsten says
"You can simply send them to Goecker, attn: Service, with a short description of what needs to be done.
You can also refer to me, so our service technician can ask me if they have any questions.
I am going on vacation from Friday, July 26th."

Carsten's contact information
carsten@goecker.dk
Direkte: 35 86 51 05
Mobil: +45 26 15 41 11

We are going to transition to working on WORKHERB0003 in the end of week 28.
@JesperMJensen please send the camera body out for maintenance (via Pakkecentralen) in week 29. 
If everything goes well with imaging on WORKHERB0003, we will plan to move WORKHERB0001 to the new, heavier load bearing table in week 30. 
If there are any issues with the camera at WORKHERB0003, there is an extra body in the cabinet.

**Comment by Gomismis** [comment]
The Fuji camera has been delivered at Goecker's today. they will email us when it's ready for pick up.

**Comment by chelseagraham** [comment]
Matilde picked up the Fuji and returned it to Priorparken on 22 August.
