### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#11]
Determine what stats we want to collect and which of these require physical tracking. Decide how to collect stats which can be sourced from the computer via tags and timestamps.

**Comment by chelseagraham** [comment]
- Entries recorded in app per (time of) session - can extrapolate records per hour, etc.
- Images taken per (time of) session - can extrapolate images taken per hour, etc.

- TIFFs exported per amount of time - can determine, on average, how long it takes to export TIFFs from a session and if this is feasible to maintain as a task for the digitizer, or needs to be included in the GUI
- Records processed through the GUI per amount of time - can determine, on average, how long the GUI needs to run for a session 
- 
- Number of cases that require attention or assistance per session of barcoding and entry into app, imaging, exporting, and running the GUI - can determine how many and what kind of obstacles are taking time to sort out

**Comment by Gomismis** [comment]
For some reason it only took 10 minutes to convert almost 300 tiffs yesterday. So I think there is no reason to be worried about that :)

**Comment by chelseagraham** [comment]
@PipBrewer Are the above stats what you had in mind, or are there any other stats you would like to add?
