### ISSUE TITLE
Specimens assigned to wrong box in Specify

### ISSUE THREAD

**Issue by RebekkaML** [NHMDenmark/Herbarium-Sheets-workstation#110]
Specimens from box 39 in the Danish Herbarium have been wrongly assigned to box 40 in Specify.
The catalog numbers that need to be in box 39 are: 928399-928471. 

This issue is very similar to another one (#94 ) and might be related.

**Comment by RebekkaML** [comment]
The problem seems to be that in the storage tree in Specify there are 2 boxes Nr. 40 and no box Nr. 39. Maybe someone trying to fix #94 accidentally renamed box 39 into 40 instead of reassigning the specimen. I tried renaming the "correct" box 39 but then it applied the change to both. But I also had some issues with specify, so that might have been a mistake. I will retry it again later.

**Comment by PipBrewer** [comment]
@RebekkaML I would add a ticket to DanSpecify board about this (or just tag Fedor or Zsuzs into this ticket) and ask if they can investigate what is going on with these boxes and advise how to proceed.

**Comment by RebekkaML** [comment]
> @RebekkaML I would add a ticket to DanSpecify board about this (or just tag Fedor or Zsuzs into this ticket) and ask if they can investigate what is going on with these boxes and advise how to proceed.

I already asked @Sosannah about this issue, she said she will have a look at it.

**Comment by Sosannah** [comment]
The collection objects in question  (928399-928471) are now assigned to box 39 in the Danish Herbarium.

I cannot handle the duplication of box 40 right now, because whenever I try to edit the storage tree my laptop is running out of memory.

![aw_snap_storage_tree](https://github.com/user-attachments/assets/97dde6c0-9c0c-4c79-87b3-1d70429c90bf)
