### ISSUE TITLE
Make additions to training document to account for exceptional cases

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#12]
We need protocols for all of these:

- [ ] Multi specimen sheets in layers
- [ ] Multi sheet specimens
- [ ] Specimens on irregular sized paper
- [ ] Mixed specimens
- [ ] Damaged specimens
- [ ] Loose specimens
- [ ] Specimens with no text
- [ ] Specimens with text on back
- [ ] Specimens with no room for the barcode label
- [ ] Specimens that already has a barcode
- [ ] Obvious erroneous specimens
- [ ] Plus of course all the tech issues we will run into
- [ ] When to use notes field

**Comment by chelseagraham** [comment]
Specimen with writing on the back:

Olof's preference is to scan the back side of a sheet on a flatbed scanner. Turning a sheet is a delicate process that he hopes to avoid.

**Comment by PipBrewer** [comment]
Conversation on multisheet specimens, waiting for further information from Olof and Christian:


[Multisheet specimens.pdf](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/10837732/Multisheet.specimens.pdf)


If the above course of action, need to ensure multiple barcode-less sheets can be accomodated in Thomas's workflow. Also need to add a request in DanSpecify for part numbering in preparations table.

**Comment by chelseagraham** [comment]
On 9 March, Christian confirmed that he, Karen and Olof agreed that they will copy labels and apply them themselves to multi-specimen sheets. They prefer that each sheet will have their own barcode, which will be associated with one another.

**Comment by chelseagraham** [comment]
**Multi specimen sheets in layers**

_if sheet with multiple fold outs_

Specimens on the sheet will receive own barcodes.
Specimens will be entered into the app independently.
A shape indicator will be used in order to process in such a way to create separate records.

**Multi sheet specimens**

_one collection across multiple sheets_

CMs will copy the label for subsequent sheets. 
Each sheet will be given its own barcode and entry in the app.
A shape indicator will be used in order to process in such a way that connects the records.

**Specimens on irregular sized paper**

_while there is a standard size of paper, there are smaller and larger exceptions_

The camera is set up on the copy stand at the highest setting to accomodate the largest sheets.
Smaller sheets will be imaged with a standard size sheet background.
Images will be processed to crop around detected sheet size.

**Mixed specimens**

_if more than one species on a sheet_

CMs should be alerted as the specimens should be remounted.
Digitizers will likely not notice this, so they will be handled as multi-specimen sheets

**Damaged / Loose specimens**

_specimens with loose bindings, debris_

Exercise caution and handle very carefully.
Only alert CMs to active (living) pest damage

**Specimens with no text**

_specimens without any information attached to them_

Species level information can be 

[ ] Specimens with text on back
[ ] Specimens with no room for the barcode label
[ ] Specimens that already has a barcode
[ ] Obvious erroneous specimens
[ ] Plus of course all the tech issues we will run into
[ ] When to use notes field

**Comment by chelseagraham** [comment]
Documentation update. Implications to Thomas' image processing noted on his GitHub.
