### ISSUE TITLE
Registering cultivated specimens in the digi app

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#124]
From Issues Log Entry 126
"Loco ignoto vel cult." folders are used for specimens that are cultivated or specimens with uncertain or no locations, that can't be placed in more specific folders.
Cultivated specimens will usually have this info on their labels, but labels of specimens of uncertain location will have very little info.
Therefor the CMs would like to be able to indicate that a specimen is from this type of folder in the Digi App.
Christian suggested adding a new location under Broad geographic region "Dania ignoto vel cult." to indicate that the specimen has unknown location within Denmark or might be cultivated.

**Comment by chelseagraham** [comment]
This was discussed at the most recent Herbarium Catch-up meeting on 12 September https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/104

As with many issues, there was a nuanced discussion about cultivated specimens to which Hannah and Jens both gave some insights and opinions. 

Hannah did not think that these species belong solely under Dania and thought it was important to connect the loco ignoto vel cult. info from the front of folders with the specimens they contain, as this is not always on the labels of the sheets. 
Jens considers registering the sheets equally as a collections management tool, so he sees the importance of being able to specify that a plant is in the Danish Herbarium, but the plant may not be from Denmark. 

**They both expressed interest in being able to generate a subset of Dania as loco ignoto vel cult. that would be separate from just Dania.** 

If this is achievable through creation of a new Broad Geographic Region, that could be an option.

In the mean time, we can plan to select Dania under Braod Geographic Region and make a QR code to scan loco ignoto vel cult. in the notes field.

**Comment by PipBrewer** [comment]
@chelseagraham If it is a new Broad Geographic Region, what is your suggestion?

**Comment by chelseagraham** [comment]
> [@chelseagraham](https://github.com/chelseagraham) If it is a new Broad Geographic Region, what is your suggestion?

Would adding punctuation in the field Dania, loco ignoto vel cult. would create a subset of data from Dania? 
Is this even necessary?

**Comment by PipBrewer** [comment]
We can dd the broad geographic region, but we would need to indicate whether the geography is restricted to Denmark or the World in the locality record (the BGR is part of a locality record - have a look at below example in Specify). 

![image](https://github.com/user-attachments/assets/89221ca6-ea05-4d74-9d8b-62af4b7ed933)

Geography is derived from a gazeteer I think and so they are standard terms. Hence, you would need to choose the level (Denmark or the World or another one). 

Once you have all agreed on the name of teh Broad Geographic Region and the Geography we can create this in Specify and in the digi app.

**Comment by chelseagraham** [comment]
OK, so if I am understanding correctly, the Broad Geographic Region field in the Digi App corresponds to a Locality record in Specify, which has fields including Locality Name, Geography, and Broad Geographic Region. It seems that the Geography and Broad Geographic are set. 

In that case, would we make a Specify Locality record with 
Locality Name: Loco ignoto vel cult.
Geography: Denmark
Broad Geographic Region: Dania

for the Loco ignoto vel cult. specimen sin the Danish Herbarium? 

These types of folders are apparently common and we should anticipate to also encounter them in the general herbarium in the future as well. Therefore we may need to similarly make new localities for Loco ignoto vel cult. specimens in other subcollections later.

**Comment by PipBrewer** [comment]
After email discussions, the following has been agreed upon:
When a digitiser comes across these specimens with "loco ignoto vel cult." on the outside of the folder, the Broad Geographic Region should be Dania and a standard note should be added to each of the notes fields for these records saying "loco ignoto vel cult.”

[20240917 RE_ Herbarium Catch-Up Meeting Notes 12 Sept.pdf](https://github.com/user-attachments/files/17031528/20240917.RE_.Herbarium.Catch-Up.Meeting.Notes.12.Sept.pdf)

Actions:
- [x] Mention to digitisers in Slack channel
- [x] Mention at next digitiser meeting
- [x] @RebekkaML to ask someone to create a standard note linked to a barcode/QR code/DM that can be scanned at the workstation
- [x] Add request to update digitisation guide next quarter to reflect new procedure (added to https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/128)
- [x] Ask Allison to incorporate this into the workflow (GREL Script). Note that the remarks table in Specify where this goes into has multiple components (the actual remark, the source, the date and whether it is valid) and so these all need to be mapped.

**Comment by beckerah** [comment]
Do we want this verbiage ("loco ignoto vel cult.") to go in the Collection Object Remarks table or would we rather it be in the Locality Remarks?

**Comment by PipBrewer** [comment]
@beckerah Good question. Would you like to ask Jens directly and do a screen shot of where in Specify object record?

**Comment by beckerah** [comment]
Per Jens & Hannah, they would like it in the Locality Remarks. I'll add updating the GREL script to my task list so we can start processing this data as requested.

**Comment by RebekkaML** [comment]
I created a barcode for "loco ignoto vel cult." and will deposit it at the Herbarium workstations tomorrow.

**Comment by beckerah** [comment]
I've now added this to the grel script, grel script documentation, and the Specify workbench mapping as localitynotes. Going forward, if "loco ignoto vel cult." is added to the notes field in the DigiApp, it will be added to the Locality and Habitat Notes field (in the Collecting Information section) of the Specify record.
