### ISSUE TITLE
Q1 2025: Requests for refinements and new features

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#127]
Please add requests for updates, refinements and new features for the three herbarium sheet workstations into this ticket.

These will be addressed and prioritised on a quarterly basis.

Next review will be in December 2024/early January 2025 for work starting January 2025.

Discussed at the Digitizer meeting 10.12.2024.

Please add full details.

**Comment by PipBrewer** [comment]
Transferred from previous quarter:
The fabric enclosing the workstation is likely to be just as heavy as a lightweight hard casing and likely to keep heat in. It also creates fibres around the workstation and cannot easily be wiped. A hard, lightweight, wipeable alternative should be sought.
Original suggestion made by PB on 25/07/2024

**Comment by RebekkaML** [comment]
We should get warm work clothing for Priorparken, there already is a ticket for this: #165 

And we should get a maintenance kit for the different stations with cleaning supplies etc.

**Comment by RebekkaML** [comment]
These suggestions were discussed at the digitizer meeting 10.12.2024.

We will implement these changes in Q1 2025:
- exchange the fabric around the enclosure for hard material that hopefully helps with ventilation (https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/171)
- buy warm work clothing for Priorparken (#165 )
- put together a maintenance kit for the workstations (though this is a lower priority than the other changes and may be pushed to the next quarter). (#157) 

Now that these are separate issues, this ticket can be closed. All further ideas / requests are to be added to the next ticket: 
https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/172
