### ISSUE TITLE
Transporting Herbarium enclosure from HERB0003 to Aarhus

### ISSUE THREAD

**Issue by RebekkaML** [NHMDenmark/Herbarium-Sheets-workstation#134]
Due to issues with vibration at the Herbarium setup in Aarhus [# 121](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/121), it was decided to deconstruct the enclosure at HERB0003 and transport it to Aarhus together with larger lights. A new enclosure will then be ordered for HERB0003 in copenhagen.

For this, I and @Gomismis will got to Aarhus either on the 23rd or 24th October, we are still waiting for confirmation on the date.

**Comment by RebekkaML** [comment]
It was decided to visit Aarhus on the 24th and 25th October 2024. The plan is for @Gomismis to drive both of us there by car on the 24th and bring the enclosure, clamps, lights and required tools with us. She will then set up the enclosure on the 24th and drive back to Copenhagen afterwards, while I (@RebekkaML ) will visit the Pinned Insects workstation at NHMA on the 24th, spend the night in Aarhus and then go to the Herbarium workstation at AU on the 25th to try out the enclosure setup.

**Comment by RebekkaML** [comment]
@Gomismis and I will go to Priorparken tomorrow (17.10.2024) and dismantle the enclosure at Herb03 for transport. This workstation won't be available for digitizing until a new enclosure has been built (#135).

**Comment by Gomismis** [comment]
New enclosure got installed in Herbarium C, Thursday 24th of October.

**Comment by RebekkaML** [comment]
During setup, the grey bottom plate of the Aarhus enclosure was scratched, which is now visible in the images. It was decided that we would send them some of the grey tape so they can cover it up again. 

To do: 

- [x] Ask @Gomismis how much / if we have any tape left
- [x] If necessary, order more of that tape, maybe also some for us.
- [x] Send tape to Aarhus
- [x] Apply to workstation

**Comment by Gomismis** [comment]
![image](https://github.com/user-attachments/assets/9170862d-8ecd-4aa6-8a92-de952b21ae74)

We have plenty of tape. I can bring it to ZM.

**Comment by RebekkaML** [comment]
I ordered some more tape directly to Aarhus yesterday, so we now both have a supply of our own. they will let me know once it has arrived and then fix the scratch in their base plate.

**Comment by RebekkaML** [comment]
During the catch up meeting yesterday, 13.11.2024, Birgitte let me know that the tape has arrived in Aarhus and they fixed the scratch in the plate with it. Chelsea had a look at the new images they took and confirmed that it is almost invisible and does not impact their image quality.
with this, the new workstation is set up completely and ready for imaging.
