### ISSUE TITLE
Catch-Up Meeting 14 November 2024

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#136]
Agenda:

**Status of re-imaging at Herbarium C**

**Use of barcodes**

**DigiApp counter request**

**Sheets containing multiple species** 

**Status of WORKHERB0003**

**Comment by RebekkaML** [comment]
This are the notes form the meeting, written by @chelseagraham and sent around by me.

[Herb20241114.pdf](https://github.com/user-attachments/files/17814658/Herb20241114.pdf)
