### ISSUE TITLE
Glare on barcodes in AU images

### ISSUE THREAD

**Issue by beckerah** [NHMDenmark/Herbarium-Sheets-workstation#147]
Several of the images coming from AU have a glare over the barcode that is causing two issues:

1. Some of the specimen images are being incorrectly identified as folders
2. Many of the barcodes are not making it into our barcode-guid matching database

The first issue is causing problems with the digitization pipeline, because it means these images need to be identified, located, and manually re-ingested. This also means that no image folders can be deleted from the workstation until we are sure all specimen images have been ingested, and they are having storage space issues which halts digitization. 

The second issue means that we have to manually pull the barcode number from the images, so it can be added to the taxonomy and locality data before the records are created in Specify. This is very time-consuming and obviously delays Specify record creation. 

Is it possible that this issue could be resolved just with a slightly updated lighting setup? @chelseagraham @RebekkaML - what are your thoughts? I can list of few images to look at, if you need the reference.

**Comment by beckerah** [comment]
Some additional information: I went through several images and it looks like there is less glare on the barcodes when they are placed as close to the center-top of the sheet as possible. Barcodes added to the very top right-hand corner and the very top left-hand corner seem to have the most glare.

**Comment by chelseagraham** [comment]
Thank you, @beckerah I'm glad you were able to get that info quickly and somewhat painlessly! @RebekkaML *if* you have some time tomorrow, would you please 1/ take a few pictures with a barcode at the right, left and center to assess the reflectivity with the new light set-up (you can move a already barcoded sheet so that the barcode is in these areas of a frame, no need to actually barcode at right, center and left for the tests) 2/if the new light set-up hasn't helped things with the AAU barcode labels being reflective, inquire with Birgitte and Charlotte if the central placement of barcode labels could be possible? OTHERWISE: I can _always_ ask Birgitte and Charlotte to try this and get back to me!

**Comment by chelseagraham** [comment]
Last week, Matilde and Rebekka brought the new enclosure out to Herbarium AAU, installed it and trained Charlotte on it. AAU has begun placing barcode labels to the middle top of the sheet. Once they are able to resume imaging at this workstation, we can see if the new set up and new placement standard remedies this issue!

**Comment by RebekkaML** [comment]
![AU barcode glare test](https://github.com/user-attachments/assets/6f2b3b76-b4f3-4c39-98e7-1606ca7e7648)

At our Aarhus visit, we also did some testing and compared the glare intensity for different barcode placements, which clearly shows that placing it in the middle solves the problem. Actually, it seems that the glare is strongest in the very corners and as long as the barcode is placed not all the way in the corner it should be readable. Below the Aarhus barcodes are some barcodes from NHMD for comparison to make sure that it is indeed a problem of material and not of light setup.

**Comment by chelseagraham** [comment]
At the Aarhus Catch-Up meeting on 6 November, Birgitte and Charlotte agreed that they would take a series of test images and send them to @chelseagraham once they are able to clear space on the local harddisk and resume imaging.

**Comment by chelseagraham** [comment]
The new placement of the barcodes toward the center of the page reduces glare on the barcodes.
