### ISSUE TITLE
Talk to IT to possibly reconfigure herbarium computer

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#15]

**Comment by chelseagraham** [comment]
On 9 March, tried to log in with DaSSCo user ID to
log in: SUA-SNM-DaSSCo01
password: zaq12Wsxcf=03

Herbarium PC:
Issue: Computer is on ScienceDomain, but not configured as KU configured machine
Resolution: Called KU IT and created a service ticket for some one to come out and reconfigure the PC.
**Follow-up: Need to back up PC and take note of software installed, transfer license for Capture One**

MADD App laptop
Issue: Computer is KU maintained, but got the error message "Your account is configured to prevent you from using this PC. Please try another PC."
Resolution: Added comment to KUIT ticket #245523.

**Comment by chelseagraham** [comment]
Data backed up on external. 
Programs noted.

**KU IT to reconfigure the computer at Priorparken on TUESDAY 21 MARCH**
