### ISSUE TITLE
Format workflow documents, separating out parts

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#17]
Imaging, digitiser and general workflow - possible separate out

The training-workflow documents should be in parts. For example, the digi app part should be separated out and common to multiple workflows. It is also best to partition individual long documents, so updating is easier e.g., the setting up, ingest etc.

Please use sectional versioning policy for these documents, keeping older versions in an archive folder.

Move all training documents to one folder

**Comment by nms419** [comment]
First edit and format done for the pinned insect guides, placed in:
**N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\GUIDES\2 Masters\Pinned Insects Guides**

First edit and format done for herbarium data entry, workflow and imaging guides. Placed in:
 **N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\GUIDES\2 Masters**

However theres still old herbarium training documents that need to be reviewed or archived. 

DaSSCo documents spreadsheet updated.

**Comment by Gomismis** [comment]
I have written and added a guide on how to create and print labels for the pinned insects. Feel free to proof read it. It is located in  
N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\GUIDES\2 Masters\Pinned Insects Guides
