### ISSUE TITLE
Sort out log in for herbarium computer and update training document

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#18]
We need to be able to log in to herbarium computer with DaSSCo log in.

This MAY require us to get it reconfigured by KUIT, so will need to contact them. We might as well get it configured as a KU computer (see attached email below) at the same time.

[RE_ Herbarium computer.pdf](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/10791402/RE_.Herbarium.computer.pdf)

**Comment by chelseagraham** [comment]
On 23 February, IT inquired about which other computers would use the general DaSSCo01 user log-in that was requested on 15 February (Incident 245523). I gave them the number for the NHMD Herbarium workstation PC.

**Comment by chelseagraham** [comment]
On 9 March, tried to log in with DaSSCo user ID to
log in: SUA-SNM-DaSSCo01
password: zaq12Wsxcf=03

Herbarium PC:
Issue: Computer is on ScienceDomain, but not configured as KU configured machine
Resolution: Called KU IT and created a service ticket for some one to come out and reconfigure the PC.
**Follow-up: Need to back up PC and take note of software installed, transfer license for Capture One**

MADD App laptop
Issue: Computer is KU maintained, but got the error message "Your account is configured to prevent you from using this PC. Please try another PC."
Resolution: Added comment to KUIT ticket #245523.

**Comment by chelseagraham** [comment]
On 9 March, tried to log in with DaSSCo user ID to
log in: SUA-SNM-DaSSCo01
password: zaq12Wsxcf=03

MADD App laptop
Issue: Computer is KU maintained, but got the error message "Your account is configured to prevent you from using this PC. Please try another PC."
Resolution: Added comment to KUIT ticket #245523.

KU IT should add this computer as a possibility for log in and hopefully will enable the log in to be used on any computer.

**Comment by chelseagraham** [comment]
I was not able to access the requested N:/ drive parent folder N:/SCI-SNM-DigitalCollections (or any subfolders of N:/) so, I added this to the ticket request for all computers.

**Comment by chelseagraham** [comment]
The SUA-SNM-DaSSCo01 account is able to log in and access the N:/ drive on the Herbarium PC (KU Asset 1022124)

The SUA-SNM-DaSSCo01 account is not able to log in or access the N:/ on the Herbarium MADD App laptop (KU Asset 1009430)

The KUIT ticket (#245523) has been updated to reflect this

**Comment by chelseagraham** [comment]
Sorted for both workstation PC tower and MADD App laptop!
