### ISSUE TITLE
Workspace for first part of workflow

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#30]
Hannah Elvery pointed out that a wide and long table is needed when barcoding sheets. The trolleys we were using were not spacious enough. There is a risk of things falling off. There is also the issue of folders slumping off the table. Others agreed. After going through the workflow, it was also agreed that to avoid confusion between imaging and app workstations (as there will be 2 lots of specimens), the app stage should be physically separate (e.g., in another room). Getting folders mixed up would be bad. There is also little space in the collections area and using trolley could block access for others and get in the way.

- [x] Investigate a place with a large table to do the app and barcoding which has internet access and is away from the imaging workstation.
- [x] Get agreement to use space.
- [x] Incorporate into training

**Comment by chelseagraham** [comment]
Investigated options 28 February. Will discuss with Christian, Olof and Karen. Large folding tables could be set up outside of or in Gringots (General Herbarium). Internet access could be an issues, but couldn't a user connect to internet and log in and then relocate to the workstation as a matter of practice?

**Comment by chelseagraham** [comment]
Agreed that we can set up card tables in Gringots (General Herbarium) where we can also have internet access.
