### ISSUE TITLE
Look into switching screens

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#33]
On 22/02/2023 there was discussion as to whether it would be better to have the live view on the right hand monitor. This is because as you reach for the next sheet (to the left), your eyes would scan the small monitor and it would be empty if that was live view, but would show the last digitised object if not live view. This provides an extra check. If it could even be zoomed into a specific area, that would check the focus is still good (hard to see with full image).
Test

**Comment by chelseagraham** [comment]
Matilde has been experimenting with rotating both screens portrait mode and is looking into a mechanism to allow the image reference monitor (ASUS) to be adjustable height, so that a digitizer may raise and lower it to their preference.

**Comment by chelseagraham** [comment]
Pip would like to know what the use case is for better quality when it should be nothing more than a quick glance over.

**Comment by Gomismis** [comment]
I think everything is alright as it is now. But it's something we should consider when we choose secondary screens for future workstations :)
