### ISSUE TITLE
Mass digitisation app documentation

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#41]
The folder for the App training document is a bit of a mess. Need to go straight to latest and have the others elsewhere (e.g., in an older versions archive folder). Also, the idea of putting a date in the title is to work from year to month to day so you can easily sort them and that goes before the person editing it (as the date modified that is automatically captured can be changed by accidentally adding a space of something to that document when opening to check something). So, need a protocol for updating and naming documents such as this.

Also, please can we clearly separate the app instructions from the rest of the workflow into separate documents

**Comment by chelseagraham** [comment]
@nms419 has worked on this. Closing as 

Format workflow documents, separating out parts
[#17](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/17)

covers this.
