### ISSUE TITLE
Initiate daily quality checks

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#43]
Initiate daily checks of Digi app data and herbarium images as well as issues log. Raise issues encountered at morning catch ups.

@chelseagraham There will be a delay in Thomas initiating the delete of the raw files on the herbarium computer. In the meantime, please review the tiff images which have been uploaded to the N drive at the end of each day. If they are all fine, you can ask the digitiser to delete the relevant days raw images on the herbarium computer. This is an interim measure until this is fixed.

**Comment by chelseagraham** [comment]
I spoke with Thomas today. It is not possible to open the .tif files in Master Storage. These files in Master Storage have been renamed with the GUID, while the raw files maintain their original names. The only way to compare the contents is to compare the number of files in a folder for a date. (The Master Storage should have 2 files for each 1 raw image.)

Thomas is able to run some automated ways to gaining confidence that resultant .tif the files in Master Storage reflect the same content as the original raw files (or the exported TIFF files, I'm not 100% certain which). This seems like the most efficient way of carrying out QC. (Even when it is possible to view the RAW and TIFF files, it is a slow process just to wait for the thumbnails to load. )

We should ask the digitizer to upload the raw files to the N:/ drive until further notice.

**Comment by chelseagraham** [comment]
Thomas created the decompress GUI which makes it possible to decompress the TIFF images that have been ingested. I did a check of 529 image files and corresponding app data and entered the corresponding data information in a  spreadsheet and updated the appropriate GitHub ticket.

Working out a schedule of spot checking regularly a few times a week.

**Comment by PipBrewer** [comment]
Please also look at mass-digitizer #438

**Comment by chelseagraham** [comment]
(https://github.com/NHMDenmark/Mass-Digitizer/issues/438)
