### ISSUE TITLE
Procure equipment and resources for second Herbarium workstation at Priorparken (barcoding and imaging) - WORKHERB0003

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#49]
- [x] Document all necessary components
- [x] Solicit feedback about possible improvements
- [x] Request quotes for equipment
- [x] Research standard table/cart options and/or inquire about custom builds
- [x] Order necessary materials
- [x] Enter in asset sheet
- [x] Set up

**Comment by chelseagraham** [comment]
@nms419 (Sara) currently working on documenting all necessary components, researching tables and carts, and finding vendors

**Comment by nms419** [comment]
List made of necessary components for workstation, can be found on the N-drive. Currently  adding links to potential suppliers. 

[Second Herbarium Workstation.docx](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/13112987/Second.Herbarium.Workstation.docx)

**Comment by chelseagraham** [comment]
@nms419 Would you please prioritize making a comparison of the following bodies: Fuji GFX 100S, Fuji GFX 100, and the new Fuji GFX 100 II - https://www.fujifilm.com/dk/en/consumer/digitalcameras/gfx prices, capture formats, any differences in sensor size, effective pixels, shutter

We may consider renting either the GFX 100 or GFX 100 II in the next couple of weeks to test and then potentially buying to use at the workstation.

**Comment by nms419** [comment]
[Fuji comparison.xlsx](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/13249295/Fuji.comparison.xlsx)

Fuji comparison made and available on the N:/SCI_DigitalCollections/DaSSCo/Workflows and workstations/Herbarium.

**Comment by nms419** [comment]
The Fuji GFX II is a more powerful camera with quicker image processing and shutter speed allowing for up to 8 fps shooting. It also has greater image stabilization and a few more capture formats, but otherwise the specs are the same as GFX100 and GFX 100s. 

None of the cameras can shoot directly into TIFF, they only allow for in camera RAW conversion. Based on this, I do not see any great advantage by changing to a new camera for the second station. I would recommend repurchasing the GFX100s, as the digitizers are familiar with this model and it would allow for easy interchangeability between the stations.

**Comment by nms419** [comment]
![KontorMoebleroffer](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/8b1d90db-ad34-4ca6-83b5-7b7508486f28)

Offer received from KontorMøbler for two tables and six office chairs.

**Comment by nms419** [comment]
KontorMøbler returned with two offers, the difference being 1.080 kr. I would therefor recommend the offer with the upgraded chair model. 
![KontorMoebleroffer](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/3c50acb8-6df6-4a04-b038-5a938ef0a3c5)

**Comment by chelseagraham** [comment]
We will go forward with ordering the second offer. Sara will put through the order via EAN with delivery to Priorparken.

**Comment by nms419** [comment]
Label dispenser from Raja arrived at ZM. @chelseagraham do we have an extra roll of barcode stickers at ZM? I would like to make sure the barcodes fit the dispenser :)

**Comment by chelseagraham** [comment]
@nms419 Please put forward the order with Reick for 2 more carts. they would have the same shipping address as the tables. I will send this info in Slack as well. 

We do not have a roll of barcode labels at ZM, unfortunately.

**Comment by nms419** [comment]
List of purchases can be found at N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\Herbarium\Second Workstation

**Comment by nms419** [comment]
Laptop, monitor and mouse received from KU IT. DaSSCo shared username has been given access.

**Comment by nms419** [comment]
**Reick** has confirmed delivery for the specimen carts in **week 4 or 5**. **KontorMøbler** has confirmed delivery for **week 4, 22/1-2024.**

**Comment by chelseagraham** [comment]
Still in communication with Carsten Grønvold regarding PC tower for imaging workstation. KU IT will no longer newly purchased support P620 towers. He will get back to me with specification on a comprable /most powerful computer that they will support.

**Comment by chelseagraham** [comment]
PC tower ordered for Herb 2 set up via KU IT (incident number 375645)
 
The specs of the computer are as follows:
30G9S2J300
ThinkStation P5
Intel® Xeon® W7-2475X (2,60GHz, 37.5MB),
Windows 11 Pro for Workstations 64,
64.0GB,
1x1TB SSD M.2 2280 PCIe Gen4 Performance TLC Opal,
2x6TB HDD SATA 3.5",
NVIDIA® RTX™ A4000 16 GB,
4YR Onsite
Pris kr. 43.074,70

**Comment by nms419** [comment]
Tables and chairs delivered til Priorparken monday 22/1.

**Comment by nms419** [comment]
Enquiries sent out to Goecker, Photographica and Scandinavian Photo. It seems the dummy battery from SmallRig is discontinued so I've also asked for alternative power supply options, but we might have to purchase that seperately.

**Comment by chelseagraham** [comment]
> Offers received from Scandinavian Photo and Goecker:
> 
> [Scandinavian Photo Quote Q0001420-0.pdf](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/14374158/Scandinavian.Photo.Quote.Q0001420-0.pdf)
> 
> Scandinavian Photo is a total of 53.695 DKK excl. VAT and cannot provide a dummy battery.
> 
> [Fuji GFX Goecker.pdf](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/14374159/Fuji.GFX.Goecker.pdf)
> 
> Goecker has various different campaigns going till 31/3 that gives a total of 15.200 DKK in discounts. The total price is 40.288 DKK excl. VAT and they can provide a dummy battery.
> 
> I talked with Kenneth Lauritzen from Goecker and he suggested at least testing the Fujinon 110mm as the 80mm is made for portraits and has some blur at the edges. @chelseagraham as far as I can tell from your writeup of the Herbarium Pilot Data, only the 63mm and the 80mm lenses were tested? Do you want to test the 110mm or just go with the 80mm?

Thank you, Sara. I think just clear this with Pip since it is such a big purchase and then go ahead from Goecker. 
Our subject is too big for the 110mm lens. We are already at max height on the stand with the 80 mm. We did consider the lens distortion between 63 and 80 when we tested. We will go forward with the 80 mm. :D

**Comment by nms419** [comment]
Niels Bo tables arrived at Priorparken 15/3.

**Comment by nms419** [comment]
Camera and lens ordered from Goecker on the 14th of March. 

Dummy battery is on back order and will be shipped out when available. 

Order received at ZM on the 22nd of march and is currently in room 453.

**Comment by nms419** [comment]
Final purchases to be made: 

- 2 monitor arms with keyboard tray for the EIZO monitor at both workstations 
- EIZO monitor
- Reference monitor (Asus ZenScreen MB165B)
- CPU bracket

These purchases will be made at DSC (corporate side of CompuMail)

- 5 x 3 meters Bosch Rexroth AluminumProfile, 40 x 40 mm
- 4 Bosch Rexroth 40 x 40 mm cubic connectors 

These materials will be purchased at RS Components. 

I have set up buisness accounts with both vendors (log in info is at my desk), however there some accounting details (like invoice address and invoice name) have been mixed up with the university's, as KU also has accounts at both places. 

I'm in dialogue with both places and will put the orders in as soon as the correct info has ben associated with the accounts. 

When these purchases have been finalized, we will need to purchase monitor connector cables for both the Eizo monitor and the reference monitor. These are readily available, so I will hold off on purchasing them untill I know how long they need to be.

**Comment by nms419** [comment]
Alu profile and cubic connectors ordered the 19/4 from RS Components, order no. 198882561. 
They cubic connectors arrived at ZM 22/4. 

DCS order put in on 18/4 and confirmed 23/4, order no. 5777137. Eizo monitor, Ergotron monitor arms and the CPUbracket arrived at ZM 24/4.

**Comment by nms419** [comment]
Asus ZenScreen arrived at ZM 26/4. Monitors and monitor arms from the DCS order has been assigned a DaSSCo number and entered into the Assets spreadsheet.
