### ISSUE TITLE
Storage error from Herbarium Ingestion Client when uploading

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#51]
From Issues Log no. 18

Herbarium GUI was left to run overnight and should shut down when finished. Next morning the PC was still on with an error mesage "No Space left on device". For now, while there is space, we dont run the GUI at the end of the day and the images are stored locally.

![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/672062eb-09e1-4c43-a608-1e2fbc2d973a)

Thomas looked at Herbarium PC and Ingestion Client. Once the ingestion issue was solved, we devised a protocol to deal with space issues on the local hard drive that may arise from the inability to ingest. TIFFs are to be exported for backlog folders just before ingestion. Jesper created a document on the Herbarium PC with the folders to be ingested as a checklist. Digitizers can export to TIFF and ingest while barcoding or export to TIFF and theningest while imaging.

**Comment by PipBrewer** [comment]
@chelseagraham It is not fully clear from the above explanation exactly what the protocol is. This needs to be added here. What exactly is our back up plan and is this a temporary solution, is there an underlying issue here?

**Comment by chelseagraham** [comment]
The list is on the local PC. 
The data is on the local PC. 
When there is a backlog, due to an error with the ingesting, the ingestion client can be run at a later date while someone is barcoding or even imaging. To save space however, we will only export to TIFF directly before ingestion. At this time, the backlog of data is only saved locally.  

It is absolutely a good idea to incorporate saving to N:/ or elsewhere as a back-up. Where/what is recommended? @bhsi-snm

**Comment by bhsi-snm** [comment]
Could ERDA be a sol with sshfs? @ThomasAlscher1991

**Comment by PipBrewer** [comment]
Pip has decided that N drive will work in lieu of a better solution for now. @chelseagraham to follow up.

**Comment by chelseagraham** [comment]
The backlog has been copied to to N:/SCI-SNM-DigitalCollections/DaSSCo/MASTER_IMAGE_STORE/Temporary storage herbarium c_20231101
