### ISSUE TITLE
Adding digitiser name to .exif data

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#53]
As a single person uploads images at end of day via the Ingestion Client, we are not currently able to see who took what and to follow up on that if there are any issues or queries. One way around this would be to add digitiser name to .exif data via CaptureOne. We would then need to extract that via the processing pipeline (so will need to pass this result and decision onto Thomas and Bhupjit). @chelseagraham to investigate at Priorparken and report back.

**Comment by chelseagraham** [comment]
We are looking into this in Priorparken. 

Just so that I understand, why do we need to pinpoint the photographer precisely? Is it ok to know it was one of two people working out at Priorparken in a day?
Could another solution be to look to the stats sheet and see that on a day, Digitizer 1 took 300 images in the AM and Digitizer 2 took 300 in the PM?

**Comment by PipBrewer** [comment]
This is information that will be stored in the storage system. Once that is up and running we will not be using the stats sheets. This is for quality assurance and training purposes. It is not sufficient to know it is one of two digitisers, especially when get more digitisers and get going at speed. We will need to be able to pinpoint issues and follow up quickly.

**Comment by chelseagraham** [comment]
Yesterday, Matilde and Sara took a couple of pictures adding different digitizer information in a metadata field in Capture One. They exported the two images to TIFF and then save the raw and the TIFF to the following directory N:/SCI-SNM-DigitalCollections/DaSSCo/Pilot Data/Herbarium Working Data/MetaDataFields/2023_Digitizer

**Comment by PipBrewer** [comment]
@ThomasAlscher1991 Could you advise as to whether it would be easy to extract this from the exif. data during the processing pipeline?

**Comment by ThomasAlscher1991** [comment]
I tested reading the exif data of the .tif files in _N:/SCI-SNM-DigitalCollections/DaSSCo/Pilot Data/Herbarium Working Data/MetaDataFields/2023_Digitizer_ with the current software (exifread) and the old software (exiftool).
I also read the .raf files with the old software (eixftool). 
I couldn't find any digitizer names in there.

Could you tell me what the tags where you used for the names and the names themselves?

**Comment by ThomasAlscher1991** [comment]
I was able to find the digitiser name MG ( I guess that stands for Mathilde Gomes). So we can read out the digitiser data from exif data (at least in .tif format).

**Comment by chelseagraham** [comment]
Can this issue be closed, or is there any further data we can provide @ThomasAlscher1991 ?

**Comment by PipBrewer** [comment]
As you know we have had issues with ensuring digitiser name is associated with the images they took, as multiple digitisers will use a specific workstation in a day. In CaptureOne we can put this info in the exif data; however, we can't do that with the Canon software. Hence, from now on, the digitisers will use the Ingestion Client in batches specific to a digitiser. Hence, no need for now to extract that from the exif data. Obviously in the future when we change the ingestion client so it runs continuously, this won't be an issue.
