### ISSUE TITLE
Protocols for Problem Sheets (use of boxes, controlled vocabulary, shapes, etc.)

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#55]
@Gomismis to upload the documentation of the outcome of meetings on 25 and 26 October within DaSSCo and with Jens Soelberg.

**Comment by Gomismis** [comment]
I'm working on the document and will upload it 13.12.23.

**Comment by Gomismis** [comment]
This is the document so far. I have send it to Pip for correction and approval. I will set it up nice when that is done. [FAQherb.docx](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/13673723/FAQherb.docx)

**Comment by Gomismis** [comment]
The document is now on the N-drive named ''Herbarium_Imaging_issues_protecol_v1.docx''
Path:
N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\GUIDES\2 Masters

The version have comments from Pip and myself. there are still a few issues that needs to be agreed on.

**Comment by PipBrewer** [comment]
Please add final version here and whether it is part of documentation at workstations and whether any training etc is being provided on it, any communications. Has this been approved by CMs? Add labels to the ticket.

**Comment by PipBrewer** [comment]
@Gomismis The document is not on the N drive and the link above doesn't work. I think you have enough information now to update the document. Please refer to https://github.com/orgs/NHMDenmark/projects/11/views/1?pane=issue&itemId=45419382

**Comment by Gomismis** [comment]
I have finalized the protocol for problem sheets so it also includes the MOS-procedure. the protocol can be found on the N-drive:
N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\GUIDES\2 Masters\Herbarium Guides

**Comment by chelseagraham** [comment]
Was eventually incorporated into guide
