### ISSUE TITLE
Adjust lighting on WORKHERB0001

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#56]
After reviewing some of the images taken of herbarium sheets (thanks to the jpegs being made as a result of [Write small script to create and save jpegs on ndrive#242](https://github.com/NHMDenmark/DaSSCo-Image-Refinery/issues/242) ) I identified issues with the quality of the images. Specifically, the images are dark and the lighting is very uneven.

- [x] Chelsea to adjust lighting so that it is even across the image
- [x] Identify reasons for dark images
- [x] How to do white balance
- [x] What other adjustments (before and after imaging) need to be incorporated into the workflow
- [x] Identify, agree and articulate quality criteria for images
- [x] Agree and implement a program of quality checking
- [x] Communicate issues to NS and KSP
- [x] Decide whether we need to retake the images

**Comment by PipBrewer** [comment]
Examples:
![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/94843484/70a27ffe-134d-4266-b44c-4b09803550a5)
![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/94843484/9381e292-da5a-45a8-a7cf-6d609330b137)

**Comment by PipBrewer** [comment]
Just had a conversation with Kim and Thomas

@ThomasAlscher1991 just mentioned that white balance can be done in post-processing.
We need a protocol for regular calibration checks e.g., white paper and measurements and tolerances
For colour profiles, we should ask CaptureOne what targets and capabilities are possible in the software and whether they have ways to do lens distortion measurements
We discussed trying a ring light perhaps in tandem with additional lights. He suggests that also perhaps at least one of the current lights may not be emitting even light. He suggests that we should re-take images, and I have forwarded details to Nikolaj for discussion.

**Comment by chelseagraham** [comment]
On 18 December, Carsten Iversen (Goecker) and photographer Marie Louise Baes met with Chelsea, Jesper and Anders at Priorparken. Carsten demonstrated Nanlux TK 200 lamps. 

<div class="text-start pb-2 pb-lg-4">
                <h2 class="h3">Specifikationer</h2>
            </div>
        <div class="tab-pane" role="tabpanel" id="specs">
            
Producent | Nanlux
-- | --
Kategori | LED lys
CRI | 96
Strøm/batteri | DC24V/10.4A Max
Lysstyrke | 1 meter: 6888 lux
Længde | 89 CM
Bredde | 54 CM
Dybde | 8.5 CM
Vægt | 5680 G
Farvetemperatur | 5600

</div>

Images from this day can be found at N:/Groupdir/SCI-SNM-DigitalCollections/DaSSCo/Pilot Data/Herbarium Working Data/231218_Herbarium_Light_Test

The suggestion was to go forward with this professional grade lights. Matilde has ordered the lights from Goecker.

These lights weigh 5.6 kg each. Given the configuration and load capacity of the scaffolding (and table), we will research alternative ways to support these light.

**Comment by chelseagraham** [comment]
![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/02e01695-1059-42e1-8003-6b856e7c08b1)
![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/7bd51453-75eb-4d7d-932f-720142cc73d3)
![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/ed1df78a-6f41-4410-84a8-af80d191a454)
![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/d391db75-130f-46e5-aed2-7000114488b1)

**Comment by chelseagraham** [comment]
The new enclosure has been set up (19 & 20 February) and tested (20 & 21 February). Images were taken and the angle and the location of the lights were adjusted in an attempt to attain within 8 pixel variance of the luminance values. 

![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/7a8473e4-19c3-4c46-ac17-208600acd711)
![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/29f7b282-8d4a-4b79-9d08-9c1c5ab8a32a)
![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/e803bd56-3e98-4dd6-9aa2-a384bc7bdb32)

These images were discussed with Kim in a meeting (26 February). The conclusion was that we would like to try to get as close to an 8 pixel variance (8/256 = 3% error) as possible, but our tolerance can be a little outside of that. 

@Gomismis @JesperMJensen 
Please attempt to get closer to an even illumination across the subject.

- Move supports away from the camera
- Move clamps toward digitizer
- Document the physical set-up by measuring the distance of the supports from the sides and the distance of the clamps from the front
- Center and clamp the imaging base (with angle )to the copystand base
- Create a new session in Capture One and save it here: SCI-SNM-DigitalCollections/DaSSCo/Workflows and workstations/Herbarium/Calibration
- Image a sheet of clean, plain white paper with the lamps at 30 degree angle
- Take the luminance values as below, In four spots within the vicintity of each corner and the middle and take an average


![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/14939397-ee97-4203-8615-f236c0019e9e)


- If necessary, adjust the angle of the lamps to 20 degrees, take a picture and assess the luminance values (the selected spot from your first sheet should carry forward
- If necessary, adjust the location of the lamps and continue to document and save images with connected information
- Continue until you have achieved even illumination. We aim for within 8 pixels as suggested by Rijksmuseum, but we can hope to get within 13 pixels (13/256 = 5% error)
- Take a screenshot of each image with the luminance values
- Annotate the screenshot for the final set-up with the average luminance values for each area and differences as above

**Comment by Gomismis** [comment]
We adjusted the lights and tracked the 'color readout' of a piece of white paper, while imaging. 
We got the best results with:
- A distance of 52 cm between the two supporting alu-profiles (marked on the profile).
- A distance of 18 cm between the clamps and the front alu_profile (marked on the supporters) 
- the Lamps at an angle of 10 degrees. 
The 'color readouts' was within 10-11 pixels.

**Comment by chelseagraham** [comment]
I'm finding this folder N:/SCI-SNM-DigitalCollections/DaSSCo/Workflows and workstations/Herbarium/Calibration/28.02.2024 Jesper og Matilde empty

**Comment by JesperMJensen** [comment]
I believe we put the relevant images here:
N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\Herbarium\Matilde\20240228_calibrate_MJG_JMJ
Is that what you are looking for? The images can be moved to the folder you mentioned.

**Comment by chelseagraham** [comment]
Moved to N:/SCI-SNM-DigitalCollections/DaSSCo/Workflows and workstations/Herbarium/Calibration/20240228_calibrate_MJG_JMJ :D

**Comment by chelseagraham** [comment]
Have added white balance, as well as adjustments used at Kew and discussed with Kim (linear response curve) in manual. Please also see https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/19

**Comment by chelseagraham** [comment]
Kim has agreed upon accepting illumination with a variance of up to 13 units (a 5% of error)

we have achieved illumination within 13 units.
Annotated image created following Calibration Protocol (https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/86) on 8 March 2024
![20240308_125thsecond_Annotated](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/8397c4e4-898d-408b-a4d5-f66ba485e861)

**Comment by chelseagraham** [comment]
Rebekka has taken the first calibration image of the set-up with the new enclosure (flame retardant material which is light gray). The illumination is still within the parameters. Please see the annotation below.

![20240314_130thsecond_Annotated](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/c41a12dc-affb-4bb8-821f-41e287b08242)
