### ISSUE TITLE
L. associated with species names

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#60]
In botany and zoology, the abbreviation L. is used to indicate Linnaeus as the authority for a species' name. In older publications, the abbreviation "Linn." is found. Perhaps this should be added to notes associated with the DigiApp guide, so digitisers know to use Linnaeus in these circumstances.

**Comment by nms419** [comment]
The taxonomic name part of the Mass Digitization App Guide has been revised. A new graphic layout has been added as well as more details regarding botanical nomenclature and the use of the abbreviation "L.". 
![image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/25056c59-00b6-47fe-accf-cb11adb4a805)
