### ISSUE TITLE
Research and order aluminum extrusion profiles as scaffolding material for new enclosure at Priorparken

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#61]
The new lights that we have ordered for Priorparken are quite heavy and we think that this will necessitate sturdier tables. Would you please

- [x] Look up the weight limit of the current tables? I think this information is on GitHub.

- [x] Research different scaffolding options that might be able to support the weight of the new light panels (https://goecker.dk/nanlux-tk-200-daylight-soft-panel). A DIKU contact recommended aluminum profile extrusion parts (Bosch Rexroth) from RS components with corner brackets like these

![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/3676127d-5d53-417c-86a0-2a08b8ff272c)

- [x] (over)Estimate the necessary weight for the imaging workstation given the established components but with the new lights and perhaps a new scaffolding system (especially if much heavier)

- [ ] See if you can find any ‘off the shelf’ tables that can accommodate the weight and are the necessary size to accommodate copystand and scaffolding

**Comment by nms419** [comment]
Aluminum profiles and connectors ordered from RS Components.
3 way cubic connectors for the corners and connector plates for cross beams.
40 x 40 mm profile was chosen so that the structure was strong enough to support the lights and whatever changes in the set up we might need in the future.  

![image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/32dd6d1c-d961-4303-b2d5-fd9481106792)

**Comment by nms419** [comment]
[Tconnectordatasheet.pdf](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/13974726/Tconnectordatasheet.pdf)
[cubicconnectordatasheet.pdf](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/13974727/cubicconnectordatasheet.pdf)
[RexrothDataSheet.pdf](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/13974728/RexrothDataSheet.pdf)

**Comment by chelseagraham** [comment]
@nms419 would you please add the weight limit information that you have looked up about our Reick table and Kontormøbler table? Afterward, we can close this ticket.

**Comment by nms419** [comment]
The weight limit of the Reick tables are 100 kg. The original estimate of the load that we would put on it was 55-75 kgs.
The current tabletop has developed a slight sag. 

![ReickWeightLimit](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/ac4bc667-3edb-4d73-8791-a2688b19950c)

The new tables for the second workstation has the same weight limit. I've double checked with the manefacturer that the MDF tabletop can take 100 kgs as well. 
![DeltaWeightLimit](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/6bb5f71d-b6cd-4cbd-aabf-1d4456789b74)

I can't find the thickness of the Reick MDF tabletops, but I'm pretty sure that they are also 22 mm like the Delta tables. Given that, it is quite possible that the Delta tables will start to sag over time as well.

**Comment by nms419** [comment]
A rough estimate of the current weight load of the Herbarium Imaging station:
![HerbariumWeightLoad](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/d755b43c-eee3-419d-ba62-8fc4801fdbc3)

If we build a new enclosure/scaffolding to the exact measurements of the current one with the Bosch RexRoth 40x40 mm alu profiles and at the new lights:
![HerbariumNewWeightLoad](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/592bd4e3-97dc-410d-a0e7-6638346c5208)

**Comment by chelseagraham** [comment]
Ordered more beams (5) per Matilde's cut plan in ticket #64 



![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/abd3cd25-0e76-4cab-ba77-dfd226e5c0ee)
