### ISSUE TITLE
Order clamps compatible with lamps and aluminum extrusion profile scaffolding

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#62]
Order clamps and necessary pins compatible with Nanlux TK200 lamps and rexroth aluminum extrusion profile.
Suggestions from Goecker include:
https://kupogrip.com/kupo-handcuff-clamp-with-16mm-stud/
https://kupogrip.com/kupo-4in-super-viser-clamp/
https://kupogrip.com/kupo-kupo-titan-clamp-with-16mm-baby-pin/
https://kupogrip.com/kupo-super-viser-clamp-with-3in-center-jaw/

**Comment by chelseagraham** [comment]
Sara will test the Kupo Convi Clamps and Kupo Baby 5/8 in (16 mm) Snap-In Pins with the aluminum extrusion profile material that she has ordered before ordering other compatible clamps.

**Comment by nms419** [comment]
Alu profiles have arrived. Our current Convi clamps do fit, but I do not think that their grip around the square profile is secure enough. 
Out of the options available from Goecker, I think the [Kupo KCP 600 4'' Super Viser clamp](https://goecker.dk/kupo-kcp-600-4-super-viser-clamp-1) would be a good fit. 
![image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/11ed80dc-be40-4a8f-bfed-290081bfabfe)
It is specifically made to mount around round or square objects, has a max load of 30 kgs and has a baby stud in one end, compatible with the new lights and a hex receiver in the other, compatible with the Convi Clamp accessories, making it very versatile.

**Comment by chelseagraham** [comment]
Please order the Kupo KCP 600 4'' Super Viser clamps, @nms419

**Comment by chelseagraham** [comment]
2 clamps ordered
