### ISSUE TITLE
Create technical drawing in Autodesk for aluminum extrusion profile scaffolding to support Nanlux TK 200 lamps

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#64]
In connection with 
**Adjust lighting on workstation 1 #56** 

 **Research and order aluminum extrusion profiles as scaffolding material for new enclosure for Herb01 at Priorparken #61** 

 **Order clamps compatible with lamps and aluminum extrusion profile scaffolding #62** 

create a technical drawing in Autodesk for aluminum extrusion profile scaffolding to support Nanlux TK 200 lamps

Solicit input from Rebekka and Jesper based on their experimentation in
 **Experiment with a lower lightbox #50** 

Information about the previous enclosure is located at
N:/SCI-SNM-DigitalCollections/DaSSCo/Pilot Data/Herbarium Working Data/Enclosure

Information about the previous Workstation is located at
N:/SCI-SNM-DigitalCollections/DaSSCo/Pilot Data/Herbarium Working Data/CG_WorkstationDiagram

**Comment by Gomismis** [comment]
[enclosure2.0.pdf](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/14116008/enclosure2.0.pdf)

Enclosure Construction Summary:

Efficiently utilize all 10 rods for 920 mm, 1220 mm, and 620 mm lengths, with minimal excess material. Additional material recommendations for an upgraded version: three extra rods required, resulting in 160 mm and 920 mm excess material. Alternatively, consider using just one additional rod for two 540 mm pieces to suspend lamps.

The detailed technical drawing and cut plan

[Cut Plan for the Enclosure.docx](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/14116012/Cut.Plan.for.the.Enclosure.docx)

 for both setups are available in the attached ticket.

**Comment by chelseagraham** [comment]
Ordered 5 more beams 



![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/daa354b1-344e-4c27-8737-a7f360690829)
