### ISSUE TITLE
Images of specimens without barcodes

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#65]
Issues Log entry no. 42
Rebekka Lesske writes "In the folder from 2023-11-08 in the Master image store, there are 2 images of specimens without a barcode. These are 7e7-a-14-0b-2b-03-0-001-00-000-0853cd-00000.jpeg and 7e7-a-14-09-25-1a-0-001-00-000-0a3dac-00000.jpeg. The same goes for one image from 2023-10-18: 7e7-9-1a-0f-2b-3a-0-001-00-000-0e43a3-00000."

**Comment by AstridBVW** [comment]
These sheets were skipped by mistake in the barcoding/digi app part of the work flow. The sheets need to be relocated in the collection and then redigitised. They should be given a barcode, the data needs to be put in the digi app, and the images needs to be retaken so we will have images with barcodes on them. Below you will find the information you need to relocate the sheets.

Image from folder 2023-11-08, 7e7-a-14-0b-2b-03-0-001-00-000-0853cd-00000:

![7e7-a-14-0b-2b-03-0-001-00-000-0853cd-00000](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/97025379/5928b053-406a-45ff-9bc2-d49d804ac575)

The taxon is Anthemis tinctoria L., and it is either stored in box 147 or 148. In the image folder it is placed between NHMD 937700 and NHMD 937703 which are in box 148.

Image from folder 2023-11-08, 7e7-a-14-09-25-1a-0-001-00-000-0a3dac-00000:

![7e7-a-14-09-25-1a-0-001-00-000-0a3dac-00000](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/97025379/c647aef9-787c-4ea3-8fec-adb887149bab)

The taxon is Anthemis austriaca Jacq., and it is stored in box 144. In the image folder it is placed between NHMD 937466 and NHMD 937464.

Data sheet for the images: 
[NHMD_Herba_20231019_16_26_SS.csv](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/14048787/NHMD_Herba_20231019_16_26_SS.csv)

Image from folder 2023-10-18, 7e7-9-1a-0f-2b-3a-0-001-00-000-0e43a3-00000:

![7e7-9-1a-0f-2b-3a-0-001-00-000-0e43a3-00000](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/97025379/92f24e45-f8fd-4b10-87a1-f3a9073d3a28)

The taxon is Chaerophyllum temulum L., and it is either stored in box 65 or 66. In the image folder it is placed between NHMD 930773 and NHMD 930775 which are in box 65.

Data sheet for image: 
[NHMD_Herba_20230926_16_01_JMJ.csv](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/14048793/NHMD_Herba_20230926_16_01_JMJ.csv)

**Comment by RebekkaML** [comment]
I gave the 3 images barcodes today and scanned them into the DigiApp (export: NHMD_Herba_20240402_14_20_RL_original). I only imaged the one in box 65, since the reimaging is already past that one. The other two sheets I didn't image yet so that they can be photographed with their box during reimaging. 

The numbers I assigned are: 

Box 65: 00947869
Box 144: 00947870
Box 148: 00947871
