### ISSUE TITLE
Source an industrial strength table to allow for development of a workstation heavier than 100 kg

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#68]
Given the continued development of the imaigng enclosure (see: https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/61) we will require a table that can support over 100 kg. Please find some options of tables that we could purchase to hold the imaging workstation.

**Comment by nms419** [comment]
A few options here:

[AJ Products, mechanic height adjustability, 150 kgs max load](https://www.ajprodukter.dk/lager-vaerksted/arbejdsborde-vaerkstedsborde/arbejdsborde/arbejdsborde-pa-hjul/mobilt-haeve-saenke-arbejdsbord-349716-349719?VAT=1)
![AJProdukter150kgs](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/34c3485f-b620-43e4-ac2f-088bde37a19e)

[Niels Bo, electric height adjustability, 240 kgs max load](https://www.nielsbo.dk/collections/lager-og-transportudstyr_arbejdsborde-pakkebe-haevesaenkeborde_haevesaenkeborde/products/2000-mm-bog-massiv-27-mm-mobilt-haeve-saenkebord)
![NielsBo240kgs](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/189ab9a8-3663-4ece-9607-a8920814df08)

[Spangkilde Industrial Lift Worktable, electric height adjustability, 400 kgs max load](https://spangkilde.dk/arbejdsbord/flytbart-arbejdsbord-400kg/) 
![Spangkilde400kgTable](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/5bde324c-002b-4d3f-b2b7-dd38139fbe69)

Note that if we forego wheels, we can get a high capacity table for a much lower price. The table could still be moved with furniture dollys and on a day to day basis, we do not move the workstations very often.
[Lomax, electric heigh adjustability, 400 kgs max load](https://www.lomax.dk/lager/lagerinventar/arbejdsborde-og-tilbehoer/arbejdsborde/arbejdsbord-elektrisk-400-kg-laminat-2000x800-mm-80134490/)
![Lomax400kgNoWheels](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/9d1fd8c3-faa4-4ee5-b63d-ba52c15f0568)

**Comment by nms419** [comment]
I'm in contact with Niels Bo, trying to get the schematics of the table. However it doesn't seem like the manufacturer provides one.

I don't think there is space to mount a tray under the table, but we could get a montior arm with a keyboard tray instead. 

I will update when Niels Bo gets back to me.

**Comment by chelseagraham** [comment]
Perfect solution, Sara. Thank you.

**Comment by nms419** [comment]
Schematics of FlexiTables 1 m leg frame. Top down view highlighted. 
![FflexiTabledimensions](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/8397603f-df45-49f5-860a-77569f166968)

There seems to be room for an undertable keyboard tray, but I still feel the safest option would be a monitor arm. This would make the use of the keyboard more flexibel as well.

**Comment by chelseagraham** [comment]
@nms419 please order 2 of the Niels Bi 240 kg max load tables to be sent to Herbarium C
