### ISSUE TITLE
Install aluminum profile scaffolding to support new lamps at WORKHERB0001

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#70]
Given https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/64 
and toward the goal of https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/56

- [x] Make arrangements to get Matilde and Sara training and access to ZM metal shop (confirmed 10:30 Tuesday 6 Feb)
- [x] Cut aluminum profile material in ZM metal shop https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/61
- [x] Make arrangements to transport materials to Priorparken (confirmed Friday 9 Feb)
- [x] Deconstruct old enclosure
- [x] Construct new scaffolding

**Comment by chelseagraham** [comment]
on 31 January, Chelsea:

emailed Thomas Hughes to request training and access for Matilde and Sara for Tuesday 6 and Wednesday 7 February

emailed Daniel Klingberg Johansson to request reservation of ZM pick-up truck for Thursday 8 or Friday 9 February
Not available either day

emailed Karsten Ølgaard Madsen to request reservation of ZM van (skjolddyret) for Thursday 8 or Friday 9 February

**Comment by nms419** [comment]
A few options for combi drills with hammer action function from RS. They all come with two batteries and a charger:

[DeWalt 12 V kombiboremaskine](https://dk.rs-online.com/web/p/boremaskiner/1925290), 1.730,30 DKK

![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/092132bf-269d-4dc3-a12b-8520a1a2306a)

Not very powerful, low capacity batteries (2 aH).

[Bosch GSB 18V-28](https://dk.rs-online.com/web/p/boremaskiner/2154940), 2.260,61 DKK

![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/a5c65937-83d9-4b53-a15e-046c77e85865)
Good option, batteries have double the capacity of the DeWalt (4 aH). Also available in an option with 5 aH batteries and various different drills that might come in handy:

[Bosch GSB18V-55](https://dk.rs-online.com/web/p/boremaskiner/2265761), 2.714,12 DKK

![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/3902d51a-da3e-4992-b30a-60a4dfda868a)

[Makita DHP451RTJ](https://dk.rs-online.com/web/p/boremaskiner/7541139), 4.348,57 DKK

![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/320ed7e6-86bc-4ded-b2b2-17f1dd156c77)

High end, more powerfull drill with 3 gears and better ergonomics.

**Comment by chelseagraham** [comment]
Need to 

- [ ] order more material
- [ ] cut material in ZM metal shop
- [ ] order drill
- [ ] make new arrangements to transport materials to Priorparken 
        ZM van (skjolddyret) reserved for Monday, 19 February but would like to get materials out there sooner. So, have reached out to Daniel about ZM pick up truck and Anders about possibly bringing materials to Priorparken when he goes out there on Thursday, 15 February if his car can accomodate the lenghts of the beams

**Comment by Gomismis** [comment]
Adjusted technical drawing for the enclosure. the enclosure needed a height adjustment to fit clamp connected lamps.

[enclosure2.0.pdf](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/14267938/enclosure2.0.pdf)

**Comment by chelseagraham** [comment]
Old enclosure will not be deconstructed because it has been requested by Lif with the understanding that we may find a purpose for it in the future
