### ISSUE TITLE
Resolve outstanding items for second NHMD workstation

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#72]
- [x] **Camera**: should we purchase another GFX100S or use the extra camera?
- [x] **Angle**: should we 3D print and embed strong magnets instead of purchasing another iron angle from Stibo? https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/73
- [ ] **Base material**: https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/8
- [x] **Side material:** should we get a lightweight solid material for the sides and fabric for the top, or use fabric for the sides and top?

**Comment by chelseagraham** [comment]
Camera: https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/49#issuecomment-1939154102

**Comment by chelseagraham** [comment]
The angle does not need to be placed at an angle. @Gomismis how much time would it take to make a 3d model, print it at DIKU and embed strong magnets?

**Comment by chelseagraham** [comment]
Side material: Best option for side material is deemed to be fabric as it gives us flexibility around the lamps, is easy to clean and is lightweight.

**Comment by Gomismis** [comment]
> Side material: Best option for side material is deemed to be fabric as it gives us flexibility around the lamps, is easy to clean and is lightweight.

I would recommend to buying four pieces of molton:
- two sides of           150 cm x 100 cm
- one backpiece of   150 cm x 200 cm
- one top piece of    150 cm x 250 cm    

I also recommend that we buy the light weight version (160 g/m2) = 1,56 kg in total. 
Molton is thick flame retardant, washable fabric used for theaters and stages. It is possible to buy molton midi clips to hang it from the construction we would need around 20 clips in total.  

Molton: 
https://www.thomann.de/dk/stairville_scenetaepper_og_molton.html?ls=100&gk=LIZUMOMW&category%5B%5D=LIZUMOMW&cme=true&manufacturer%5B%5D=Stairville&bn=Stairville    

Clips:
https://www.thomann.de/dk/holdon_midi_clip_black_12pcs_pack.htm

**Comment by Gomismis** [comment]
> Angle: The angle does need to be placed at an angle. I estimate a 20 degree angle. @Gomismis how much time would it take to make a 3d model, print it at DIKU and embed strong magnets?

It would take me 1-2 days to draw and print

**Comment by chelseagraham** [comment]
Angle: We will opt for 2 custom created 3d modeled and printed angles

**Comment by chelseagraham** [comment]
> > Side material: Best option for side material is deemed to be fabric as it gives us flexibility around the lamps, is easy to clean and is lightweight.
> 
> I would recommend to buying four pieces of molton:
> 
>     * two sides of           150 cm x 100 cm
> 
>     * one backpiece of   150 cm x 200 cm
> 
>     * one top piece of    150 cm x 250 cm
> 
> 
> I also recommend that we buy the light weight version (160 g/m2) = 1,56 kg in total. Molton is thick flame retardant, washable fabric used for theaters and stages. It is possible to buy molton midi clips to hang it from the construction we would need around 20 clips in total.
> 
> Molton: https://www.thomann.de/dk/stairville_scenetaepper_og_molton.html?ls=100&gk=LIZUMOMW&category%5B%5D=LIZUMOMW&cme=true&manufacturer%5B%5D=Stairville&bn=Stairville
> 
> Clips: https://www.thomann.de/dk/holdon_midi_clip_black_12pcs_pack.htm

Matilde ordered

**Comment by chelseagraham** [comment]
@Gomismis please follow up on the base material when you have the chance. https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/8

I am closing this ticket.
