### ISSUE TITLE
3D model the angle

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#73]
3D model the angle with a 20 degree rise where the Object Level target is placed. Model the angle to include embedded the small, strong magnets.

More information about the angle is located here:
![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/9e3aec00-9abc-457a-8e22-3269d7914c30)
(The institutional top bar and scale bar are not the same thickness as the object level target. They are thinner, but the difference in thickness isn't something we need to account for.)
(The metal angle that we had made for us by Stibo is 2 mm thick)

![Image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/108529653/ece89e2c-53e9-4973-af42-fbdcc0e34feb)

**Comment by chelseagraham** [comment]
@nms419 or @RebekkaML tomorrow, 23 February, please take a series of pictures of a white sheet of paper (two each for the following scenarios) with the color target flat (2), at a 10 degree angle (2), at a 20 degree angle  (2), and at a 30 degree angle (2). 

Please look at the guide here:
SCI-SNM-DigitalCollections/DaSSCo/Workflows and workstations/GUIDES/Herbarium/HerbariumImaging/
for updated settings to the camera. 
Please apply edits from the guide ( #56, #57, and #58 ) to the second image of each pair and keep the first totally raw before exporting
Please rename the files with _flat, _10degree, _20degree, _30 degree and _flatedit, _10degreeedit, _20degreeedit, _30degreeedit
Please export to TIFF
Please save the files here: N:/SCI-SNM-DigitalCollections/DaSSCo/Pilot Data/Herbarium Working Data/20240223/ColorTarget

**Comment by RebekkaML** [comment]
I took the images as requested and saved them in the specified folder.

**Comment by chelseagraham** [comment]
From Rebekka's images, it looks like only a 10 degree angle tilt is necessary and yields the least distortion.

**Comment by chelseagraham** [comment]
After discussion and some testing about the impact of shutterspeed on the target, Kim approves the 10 degree tilt of the Object Level target on the angle.
[Re: Test data from Herbarium C_1.pdf](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/14590398/Re.Test.data.from.Herbarium.C_1.pdf)
[Re: Test data from Herbarium C.pdf](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/14590401/Re.Test.data.from.Herbarium.C.pdf)

**Comment by Gomismis** [comment]
The angle has been modeled and is ready for printing, but there is a bit of a backlog on DIKU's side. Morten is busy, and all the 3D printers are in use most days.

**Comment by chelseagraham** [comment]
Matilde has 3D printed the first version of the angle. She will take it to Priorpakren on Friday 12 April to test, make alterations to the 3D model and re-print with DIKU.

**Comment by Gomismis** [comment]
Angles are printed for Herb0001 and Herb0003.  I have also uploaded  technical drawing in this ticket

[Herb_Angle_v3.pdf](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/15500270/Herb_Angle_v3.pdf)
