### ISSUE TITLE
Add Protocol for Multiple Specimen Object with a Preparation to Imaging Guide

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#75]
From an email Sara wrote on 21 February, 
>>
Another unrelated issue I've mostly found with the dung beetles is that sometimes a specimen will be both a multiple specimen object and have slide preparations, making it a multi object specimen as well. 
 
As we can only activate one button in the digi app, I've used the 'multi specimen object' button and written the slide number in the notes, but it would be great to have a set protocol for these cases.
<<

@nms419 Please add this protocol to the Imaging Guide and also as a resolved issue on the issues log

**Comment by nms419** [comment]
Pinned Insects Workflow Guide SS 1st edit 20231206 edited to include this protocol.
