### ISSUE TITLE
Herbarium sheets assigned to wrong storage box in Specify

### ISSUE THREAD

**Issue by RebekkaML** [NHMDenmark/Herbarium-Sheets-workstation#76]
While going through the collection boxes to fill in the author names spreadsheet ( #74 ), I noticed that some specimens were saved under the wrong box in the spreadsheet. This mistake is also in Specify. 

The catalogue numbers 00928110-00928209 (Species Amaranthus thunbergii Moq., Amaranthus viridis L. and Gomphrena globosa L.) are stored in box 36, but in Specify they are assigned to box 35. 
This probably happened because a Digitizer forgot to change the storage location when starting on an new box. 

For easier access to the specimens, this mistake should be corrected in Specify.

**Comment by AstridBVW** [comment]
This is now fixed. Because it was 100 records that needed to be corrected, it would have taken a while to do it manually in Specify. Instead I got Fedor to help me, and he corrected it directly in the SQL.
