### ISSUE TITLE
DaSSCO Herbarium Digitisation Catch-up Meeting 2024_February_29

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#77]
Discuss 

- Transcription

- https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/58
"@Gomismis in her report on problem specimens in Botany, mentioned an example of multiple species on the same herbarium sheet. Equally, a species could have been re-identified at some point (or could be, following digitisation) and its location within the collection may not have been changed at that point. As being able to locate specimens depends on the specimens being filed under their correct name, in the above examples there may be difficulty locating the specimen. Would it not be a good idea, when using the front of folders to get taxon information, to indicate in Specify that these are the names that the specimens are filed under? This would be especially useful if a specimen has been reidentified multiple times. Finding it in the collection, you need to know which name to look under. So my proposal is - would collection managers and curators be happy if against the taxon determination in Specify, we always indicate that this is the name it is filed under? There is already an existing field in Specify for NHMD vascular plants we could use for this purpose."

**Comment by RebekkaML** [comment]
Here are the notes taken from the meeting: 

[DaSSCo Herbarium Digitization meeting 29-02-2024.pdf](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/14535895/DaSSCo.Herbarium.Digitization.meeting.29-02-2024.pdf)
[DaSSCo Herbarium Digitization meeting 29-02-2024.docx](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/14535896/DaSSCo.Herbarium.Digitization.meeting.29-02-2024.docx)

They are also on the N-Drive: N:\SCI-SNM-DigitalCollections\DaSSCo\Transcription\DaSSCo Herbarium Catch-Up meeting 29.02.2024

**Comment by chelseagraham** [comment]
@Astrid please give an update when the user stories document has been updated with information from this meeting
