### ISSUE TITLE
Update Herbarium C Cheat Sheet Imaging Guide

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#83]
- [x] Please update the cheat sheet guide @ N:/SCI-SNM-DigitalCollections/DaSSCo/Workflows and workstations/GUIDES/2 Masters/Herbarium Guides/Herberium Imaging Guide 1st edit SS 20231215.docx with information from N:/SCI-SNM-DigitalCollections/DaSSCo/Workflows and workstations/GUIDES/Herbarium/HerbariumImaging/HerbariumC_DigiTrainingDoc_20240305_cg.docx (or most recent date)
- [x] Please update the full guide N:/SCI-SNM-DigitalCollections/DaSSCo/Workflows and workstations/GUIDES/Herbarium/HerbariumImaging/HerbariumC_DigiTrainingDoc_20240305_cg.docx (or most recent date) with images of problem sheets (where IMAGE is written in caps and highlighted in yellow)

**Comment by chelseagraham** [comment]
- [ ] Please ensure that the MOS data matrix protocol is correct in the final guides ( as the test data has been successful https://github.com/NHMDenmark/DaSSCo-Image-Refinery/issues/255)

**Comment by nms419** [comment]
MOS data matrix protocol added:
![image](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/assets/146927054/fe64b51f-9e06-48be-a666-5019044955c8)

**Comment by nms419** [comment]
Merging cheat sheet with the full guide, moving intial set up of camera to the end of the document, for one, complete guide.

The document can currently  be found at: N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\GUIDES\2 Masters\Herbarium Guides

Under  "Herberium Workflow+Cheat Sheet Merge SS 20240307.docx"

The document has received the first rough edit after merging. Next screenshots and images need to be updated.

**Comment by nms419** [comment]
Edit complete, final document named as "Herbarium Imaging Guide 2nd edit 20240411" under "2 Masters" in the Guide folder. Guide is undergoing review by the digitisers and will be printed and placed by the workstations end of April.
