### ISSUE TITLE
Take first set of images with new settings on WORKHERB0001

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#84]
Since lights are getting quite hot in the enclosure, experiment with intensity settings on the lamps.

- Start with 1/30th of a second shutter speed with 75% brightness on the lamps and test a little bit with a herbarium sheet. You can make the shutter speed longer (1/25th, etc.) if the image is too dark. You can look at the curve under Exposure Evaluation in the left hand side panel, and/or use the Exposure Warning button in the top right hand side panel.

- Once you have the appropriate settings, take a picture of a white sheet of paper that we can assess for evenness of illumination.

- Then take 100 images. 

- Export the images with the usual edits (ICC color profile matching the camera, white balance) to TIFF.

- Then apply the linear response curve and export again with the extension _ed

- Save the session and images to N:/SCI-SNM-DigitalCollections/DaSSCo/Pilot Data/Herbarium Working Data/20240308

- Save the test shots you took in order to determine the shutter speed in the Session as well, but do not worry about editing or exporting them

**Comment by chelseagraham** [comment]
- Take images with 1/25th of a second, 1/30th of a second and 1/40 of a second shutter speeds with 75% brightness on the lamps for 20 herbarium sheets.

- Export the images with the usual edits (ICC color profile matching the camera, white balance) to TIFF.

- Save the session and images to N:/SCI-SNM-DigitalCollections/DaSSCo/Pilot Data/Herbarium Working Data/20240312/Shutter speed tests

**Comment by nms419** [comment]
Images taken and stored in subfolders in N:/SCI-SNM-DigitalCollections/DaSSCo/Pilot Data/Herbarium Working Data/20240312/Shutter speed tests.
