### ISSUE TITLE
Record subspecies, variety, forma etc. for boxes 1-285 in Herbarium C

### ISSUE THREAD

**Issue by RebekkaML** [NHMDenmark/Herbarium-Sheets-workstation#91]
This was originally part of #74 , but got it's own Issue now.
Also similar to #88.

At the beginning of digitization, any taxa below species level given on the herbarium folders were ignored and not entered into the DigiApp. This was because the App and import pipeline did not support this in the beginning, so digitizers were told not to include it.
It is possible to record this now, but we are still missing this information from the boxes that are already digitized (1-285).
Therefore, we need to go back through these boxes and record the subspecies taxon information.

The collection managers seem to agree that this should be included now (#88 ).

The first idea was to note down the first and last barcode number of each affected folder and then update everything in between to the correct taxon, but there are many specimens that don't follow that order, e.g. when they got a new barcode to fix a mistake. 

Suggestion by @PipBrewer:
Export all DaSSCo specimens (up to box 285) from Specify with their barcodes to make sure we don't miss anything, and then go through the boxes again like we did for the author spreadsheet. But we still need to discuss the details of how this could work.

**Comment by PipBrewer** [comment]
Just to clarify, it was never policy to ignore taxa below species level. This was a miscommunication issue.

**Comment by RebekkaML** [comment]
The current plan to solve this problem is: 

1. Export all taxa from boxes 1-285, then query the entirety of Specify for all their possible child records. We might need to ask Fedor for help with this. (Alternatively, we can just see what we find on the folder names and type it all out, which approach is better?) Also, it is possible that we won’t catch everything with the Specify query.

2. Create a new spreadsheet with specimen barcode numbers, and add the already filled in author names to this. There is a function in Excel that can do this. Here, we also implement what we decided on with Jens regarding author names (#90 ). Then we rearrange the sheet, order by box and barcode, and try to make it overall easier to use. 

3. Check for outliers (barcodes that are not in consecutive order). We can’t check every single one of them, and as we don’t know which folder they were in, we just leave it without subspecies etc.

5. Go to Priorparken, fill everything in. It will be a long, ungainly spreadsheet, we need to make this usable. Maybe we should make hourly save files of it? Also, can we collapse parts like separate boxes?

**Comment by RebekkaML** [comment]
I finished creating a spreadsheet and started filling it in today. It has been agreed that every digitizer will take around 1h of their digitization time at Priorparken to fill in this spreadsheet. 

The spreadsheet and instructions are located on the N-Drive: "N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\Herbarium\Infraspecies spreadsheet"

They are also uploaded here:  


[Infraspecies_Table_original.xlsx](https://github.com/user-attachments/files/16388928/Infraspecies_Table_original.xlsx)



[Infraspecies_table_guide.docx](https://github.com/user-attachments/files/16388934/Infraspecies_table_guide.docx)

**Comment by RebekkaML** [comment]
The infraspecies spreadsheet has now been completely filled out. Some last issues need to be resolved and then it can be imported into Specify. I created a separate Issue for that: #117 

Here is the completed spreadsheet: 
[Infraspecies_table_completed.xlsx](https://github.com/user-attachments/files/18425616/Infraspecies_table_completed.xlsx)
