### ISSUE TITLE
Herbarium sheets assigned to wrong storage box in Specify (39 instead of 40)

### ISSUE THREAD

**Issue by RebekkaML** [NHMDenmark/Herbarium-Sheets-workstation#94]
The same problem as in #76 

The taxon Aegopodium podagraria is stored in Box 40 at the Herbarium, but is assigned to box 39 in Specify.
This concerns exactly 100 entries, Nr. 000928472 - 000928570 and 000928572.
This mistake should be fixed in Specify.

**Comment by AstridBVW** [comment]
Similar to ticket #76 this is most easily fixed directly in the database instead of from the UI side. Fedor is on vacation, I have contacted Zsuzsanna to see if she has time to help with this.

**Comment by AstridBVW** [comment]
It turned out that it was only record 000928572 that had the wrong box number, the rest were already associated with box 40. It has now been corrected.
