### ISSUE TITLE
3D print an angle for AAU Herbarium

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#97]
3D print label angle for AAU herbarium

**Comment by Gomismis** [comment]
There is issues with all four 3D-printers at DIKU, I'm waiting for Morten to return from vacation. Meanwhile I will look into getting our 3D-prints printed elsewhere.

**Comment by Gomismis** [comment]
done and will be send til AUU ASAP with the rest of the prints.
