### ISSUE TITLE
Update Mass Digitization App Guide to include software installation directions for NHMA

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#98]
Please update guide for non shared PCs, as in Aarhus

**Comment by nms419** [comment]
And update for the Digi App Guide is in process and can be found here: N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\GUIDES\Editing in process. 

I've tried to add distinctions between NHMD steps and AAU steps but there are a number of AAU processes I am unsure about.

**Comment by chelseagraham** [comment]
I will ask Charlotte if she can fill in the blanks for NHMA based on their specific set-up (computer, onedrive, etc.).
