### ISSUE TITLE
Incorporate a convention for naming white balance presets and protocol for deleting presets once per month in the Herbarium Imaging Guide

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#99]
From issues log no. 90 

"At Herb01 we save a custom White Balance Preset for each session. The folder where these are saved is becoming quite bloated and it is difficult to find the relevant preset. 
Could we have just one universal preset that we use each session? If not, could we introduce a protocol to delete old presets or a specific naming protocol for them?"

In response, I propose that we 

- create a convention for naming the white balances with the date YYYYMMDD, AM (morning) /PM (afternoon), and initials of the digitizer. For example, 20240517_PM_CG

- introduce a protocol of deleting all of the old presets once per month, whoever is working in the first week of the month, please look to see about deleting them (hopefully the first person has, but just in case)

- incorporate these both into the current Herbarium Imaging Guide with a screenshot (if deemed necessary) of the naming and the filepath for the storage location for all these presets from which they should be deleted a the beginning of each month.

**Comment by nms419** [comment]
A new edit of the Herbarium Imaging Guide has been made to incorporate this protocol. It can be found at N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\GUIDES\Editing in process. 

A rough outline of the protocol has been added under "Finishing the imaging session", but the protocol needs to be tested practically before a final edit can be made. 

Will update as the protocol develops.
